//go:build interop_python

package rns

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"
)

// TestIFACSealedFromUpstreamRNS feeds our parser real IFAC-sealed wire
// bytes generated by upstream RNS 1.2.0's actual Transport.transmit IFAC
// sealing path (verbatim from RNS/Transport.py:993-1024). Confirms:
//
//  1. The unsealed version of the same packet parses cleanly — proves the
//     wire bytes are otherwise valid and the rejection isn't a false
//     positive on malformed input.
//  2. The IFAC-sealed version is rejected with errIFACUnsupported — proves
//     our parser correctly identifies the bit-7 flag set by upstream's
//     IFAC sealer (line 1013: `byte ^ mask[i] | 0x80` forces bit 7 even
//     after masking).
//
// Build-tagged so it doesn't run in plain `go test ./...` — invoke with
//
//	go test -tags interop_python ./internal/rns/...
//
// Skipped (not failed) if `python` or upstream RNS isn't available, so a
// developer without the Python toolchain can still run the rest of the
// suite.
func TestIFACSealedFromUpstreamRNS(t *testing.T) {
	pythonExe := "python"
	if runtime.GOOS == "windows" {
		// On Windows `python.exe` resolves; nothing else needed.
	}
	scriptPath := filepath.Join("..", "..", "scripts", "gen_ifac_packet.py")

	out, err := exec.Command(pythonExe, scriptPath).Output()
	if err != nil {
		t.Skipf("python helper unavailable (%v); install RNS 1.2.0 to run this test", err)
	}

	var v struct {
		UnsealedHex   string `json:"unsealed_hex"`
		IFACSealedHex string `json:"ifac_sealed_hex"`
		IFACSize      int    `json:"ifac_size"`
	}
	if err := json.Unmarshal(out, &v); err != nil {
		t.Fatalf("decode python output: %v\nstdout=%s", err, out)
	}

	unsealed, err := hex.DecodeString(v.UnsealedHex)
	if err != nil {
		t.Fatalf("decode unsealed_hex: %v", err)
	}
	if _, err := ParsePacket(unsealed); err != nil {
		t.Fatalf("unsealed packet should parse cleanly, got %v", err)
	}

	sealed, err := hex.DecodeString(v.IFACSealedHex)
	if err != nil {
		t.Fatalf("decode ifac_sealed_hex: %v", err)
	}
	if sealed[0]&0x80 == 0 {
		t.Fatalf("python helper emitted sealed packet without IFAC bit set: 0x%02x", sealed[0])
	}
	if _, err := ParsePacket(sealed); !errors.Is(err, errIFACUnsupported) {
		t.Errorf("ParsePacket(ifac-sealed): err=%v, want errIFACUnsupported", err)
	}
}
