package rns

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"testing"
)

// Resource wire-byte interop: parse fixtures generated by upstream
// RNS via testdata/resource_interop/generate.py. The outside-oracle
// guarantee is what catches "compiles and round-trips with itself but
// silently disagrees with reference" bugs that pure round-trip tests
// can't see (memory: test against an outside oracle).

func loadFixture(t *testing.T, name string) []byte {
	t.Helper()
	path := filepath.Join("testdata", "resource_interop", name)
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture %s: %v (re-run testdata/resource_interop/generate.py)", path, err)
	}
	return b
}

func TestInteropParseUpstreamADV(t *testing.T) {
	body := loadFixture(t, "adv_minimal.bin")
	adv, err := ParseResourceAdv(body)
	if err != nil {
		t.Fatalf("ParseResourceAdv: %v", err)
	}
	if adv.TransferSize != 544 {
		t.Errorf("t=%d, want 544", adv.TransferSize)
	}
	if adv.DataSize != 484 {
		t.Errorf("d=%d, want 484", adv.DataSize)
	}
	if adv.NumParts != 3 {
		t.Errorf("n=%d, want 3", adv.NumParts)
	}
	if !bytes.Equal(adv.Hash, bytes.Repeat([]byte{0x11}, 32)) {
		t.Errorf("h mismatch: %x", adv.Hash)
	}
	if !bytes.Equal(adv.RandomHash, []byte{0xAA, 0xBB, 0xCC, 0xDD}) {
		t.Errorf("r mismatch: %x", adv.RandomHash)
	}
	if adv.SegmentIndex != 1 || adv.TotalSegments != 1 {
		t.Errorf("i/l = %d/%d, want 1/1", adv.SegmentIndex, adv.TotalSegments)
	}
	if !adv.HasFlag(ResourceFlagEncrypted) {
		t.Errorf("encrypted flag not set in upstream-encoded ADV")
	}
	if adv.HasFlag(ResourceFlagCompressed) {
		t.Errorf("compressed flag should NOT be set in adv_minimal")
	}
	if adv.RequestID != nil {
		t.Errorf("request_id should be nil for non-RPC resource, got %x", adv.RequestID)
	}
}

func TestInteropParseRejectsCompressed(t *testing.T) {
	// Stage-6 audit: c=1 (bz2-compressed) ADVs are rejected to
	// prevent decompression-bomb attacks. fwdsvc has no use case for
	// compressed inbound resources — every legitimate inbound is an
	// LXMF DM body well under the per-message limit. If a real need
	// for compressed inbound appears, replace the reject with bounded
	// bz2.NewReader(io.LimitReader(...)) decompression in
	// ResourceReceiver.assemble.
	body := loadFixture(t, "adv_compressed.bin")
	_, err := ParseResourceAdv(body)
	if err == nil {
		t.Fatal("expected c=1 ADV to be rejected, got nil error")
	}
	if !errors.Is(err, ErrResourceTooLarge) {
		t.Errorf("expected ErrResourceTooLarge wrap, got %v", err)
	}
}

func TestInteropParseUpstreamREQNotExhausted(t *testing.T) {
	body := loadFixture(t, "req_not_exhausted.bin")
	req, err := ParseResourceReq(body)
	if err != nil {
		t.Fatalf("ParseResourceReq: %v", err)
	}
	if req.Exhausted {
		t.Error("Exhausted should be false")
	}
	if !bytes.Equal(req.ResourceHash, bytes.Repeat([]byte{0x22}, 32)) {
		t.Errorf("resource_hash mismatch: %x", req.ResourceHash)
	}
	if len(req.RequestedMap) != 2 {
		t.Fatalf("requested_map len = %d, want 2", len(req.RequestedMap))
	}
	if !bytes.Equal(req.RequestedMap[0], []byte{0x01, 0x02, 0x03, 0x04}) {
		t.Errorf("requested[0] = %x, want 01020304", req.RequestedMap[0])
	}
	if !bytes.Equal(req.RequestedMap[1], []byte{0x05, 0x06, 0x07, 0x08}) {
		t.Errorf("requested[1] = %x, want 05060708", req.RequestedMap[1])
	}
}

func TestInteropParseUpstreamREQExhausted(t *testing.T) {
	body := loadFixture(t, "req_exhausted.bin")
	req, err := ParseResourceReq(body)
	if err != nil {
		t.Fatalf("ParseResourceReq: %v", err)
	}
	if !req.Exhausted {
		t.Error("Exhausted should be true")
	}
	if !bytes.Equal(req.LastMapHash, []byte{0xDE, 0xAD, 0xBE, 0xEF}) {
		t.Errorf("last_map_hash mismatch: %x", req.LastMapHash)
	}
	if !bytes.Equal(req.ResourceHash, bytes.Repeat([]byte{0x33}, 32)) {
		t.Errorf("resource_hash mismatch: %x", req.ResourceHash)
	}
	if len(req.RequestedMap) != 0 {
		t.Errorf("exhausted request should have no requested_map, got %d", len(req.RequestedMap))
	}
}

func TestInteropParseUpstreamHMU(t *testing.T) {
	body := loadFixture(t, "hmu_segment2.bin")
	hmu, err := ParseResourceHmu(body)
	if err != nil {
		t.Fatalf("ParseResourceHmu: %v", err)
	}
	if !bytes.Equal(hmu.ResourceHash, bytes.Repeat([]byte{0x44}, 32)) {
		t.Errorf("resource_hash mismatch: %x", hmu.ResourceHash)
	}
	if hmu.SegmentIndex != 2 {
		t.Errorf("segment_index = %d, want 2", hmu.SegmentIndex)
	}
	if !bytes.Equal(hmu.HashmapBytes, []byte{0xAB, 0xCD, 0xEF, 0x01}) {
		t.Errorf("hashmap mismatch: %x", hmu.HashmapBytes)
	}
}

func TestInteropParseUpstreamPRF(t *testing.T) {
	body := loadFixture(t, "prf.bin")
	prf, err := ParseResourceProof(body)
	if err != nil {
		t.Fatalf("ParseResourceProof: %v", err)
	}
	if !bytes.Equal(prf.ResourceHash, bytes.Repeat([]byte{0x55}, 32)) {
		t.Errorf("resource_hash mismatch: %x", prf.ResourceHash)
	}
	if !bytes.Equal(prf.FullProof, bytes.Repeat([]byte{0x66}, 32)) {
		t.Errorf("full_proof mismatch: %x", prf.FullProof)
	}
}

func TestInteropParseUpstreamCancel(t *testing.T) {
	body := loadFixture(t, "cancel.bin")
	rh, err := ParseResourceCancel(body)
	if err != nil {
		t.Fatalf("ParseResourceCancel: %v", err)
	}
	if !bytes.Equal(rh, bytes.Repeat([]byte{0x77}, 32)) {
		t.Errorf("resource_hash mismatch: %x", rh)
	}
}

// Outbound: our packed ADV must round-trip through upstream's
// unpacker. Check by re-parsing it ourselves (good for regression),
// and by ensuring it's at least the same byte count as the upstream
// fixture for an equivalent ADV (catches gross msgpack mistypings).
func TestInteropOurADVMatchesUpstreamShape(t *testing.T) {
	upstreamBytes := loadFixture(t, "adv_minimal.bin")

	h := bytes.Repeat([]byte{0x11}, 32)
	r := []byte{0xAA, 0xBB, 0xCC, 0xDD}
	adv := &ResourceAdvertisement{
		TransferSize:  544,
		DataSize:      484,
		NumParts:      3,
		Hash:          h,
		RandomHash:    r,
		OriginalHash:  h,
		SegmentIndex:  1,
		TotalSegments: 1,
		Flags:         int(ResourceFlagEncrypted),
		Hashmap:       []byte{0xCA, 0xFE, 0x00, 0x01, 0xCA, 0xFE, 0x00, 0x02, 0xCA, 0xFE, 0x00, 0x03},
	}
	ours, err := PackResourceAdv(adv)
	if err != nil {
		t.Fatalf("PackResourceAdv: %v", err)
	}
	// Sanity: byte count within ±2 of upstream — different msgpack
	// libraries may pick slightly different int widths or map
	// orderings, but the gross size should match. A 10x difference
	// would indicate a structural mistake.
	if abs(len(ours)-len(upstreamBytes)) > 8 {
		t.Errorf("packed ADV size %d, upstream %d (delta > 8 bytes — investigate msgpack typing)", len(ours), len(upstreamBytes))
	}
	// Critical: upstream MUST be able to parse our bytes (we test
	// the inverse via fixtures above; this side closes the loop).
	parsed, err := ParseResourceAdv(ours)
	if err != nil {
		t.Fatalf("our ADV fails self-parse (definitely won't interop): %v", err)
	}
	if parsed.TransferSize != adv.TransferSize {
		t.Errorf("self-parse t=%d, want %d", parsed.TransferSize, adv.TransferSize)
	}
}

func abs(x int) int {
	if x < 0 {
		return -x
	}
	return x
}

// Defensive: a malformed-msgpack ADV body must surface as
// ErrResourceADVMalformed, not panic.
func TestInteropMalformedADVNoPanic(t *testing.T) {
	for _, body := range [][]byte{
		nil,
		{},
		{0x00},
		bytes.Repeat([]byte{0xFF}, 1024),
	} {
		_, err := ParseResourceAdv(body)
		if err == nil {
			t.Errorf("expected error for malformed body %x", body)
			continue
		}
		if !errors.Is(err, ErrResourceADVMalformed) {
			t.Errorf("err = %v, want wrapped ErrResourceADVMalformed", err)
		}
	}
}
